### PR TITLE
Upgrade Dotty to 3.0.1

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Comment by prolativ** [comment]
@anatoliykmetyuk I'll need to get this PR merged for me as I don't have any privileges in this repo

**Comment by anatoliykmetyuk** [comment]
I've invited you to the repo – you need to check your email and accept the invite. Let me know if you still can't merge after that.

**Comment by prolativ** [comment]
@anatoliykmetyuk thanks, although with the permissions granted all I could do was to assign you as a reviewer 😄

**Comment by anatoliykmetyuk** [comment]
Ok, should have the merge permissions now

**Pull request merged**
